// <auto-generated />
using System;
using FinGrow.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FinGrow.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(FinGrowDbContext))]
    [Migration("20260906154849_AddTransactionStatus")]
    partial class AddTransactionStatus
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FinGrow.Domain.Entities.Budget", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("period");

                    b.Property<DateOnly>("PeriodStart")
                        .HasColumnType("date")
                        .HasColumnName("period_start");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_budgets");

                    b.HasIndex("EmployeeId", "Category", "PeriodStart")
                        .IsUnique()
                        .HasDatabaseName("ix_budgets_employee_id_category_period_start");

                    b.ToTable("budgets", null, t =>
                        {
                            t.HasCheckConstraint("ck_budgets_limit_positive", "limit_amount > 0");
                        });
                });

            modelBuilder.Entity("FinGrow.Domain.Entities.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DefaultCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("default_currency");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("password_hash");

                    b.Property<string>("TaxId")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("tax_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_companies");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_companies_email");

                    b.HasIndex("TaxId")
                        .IsUnique()
                        .HasDatabaseName("ix_companies_tax_id");

                    b.ToTable("companies", (string)null);
                });

            modelBuilder.Entity("FinGrow.Domain.Entities.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("ManagerName")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("manager_name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_departments");

                    b.HasIndex("CompanyId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_departments_company_id_name");

                    b.ToTable("departments", (string)null);
                });

            modelBuilder.Entity("FinGrow.Domain.Entities.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("department_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_name");

                    b.Property<DateOnly>("HiredOn")
                        .HasColumnType("date")
                        .HasColumnName("hired_on");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("phone_number");

                    b.Property<string>("PreferredCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("preferred_currency");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_employees");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("ix_employees_company_id");

                    b.HasIndex("DepartmentId")
                        .HasDatabaseName("ix_employees_department_id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_employees_email");

                    b.ToTable("employees", (string)null);
                });

            modelBuilder.Entity("FinGrow.Domain.Entities.Goal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AchievedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("achieved_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("Deadline")
                        .HasColumnType("date")
                        .HasColumnName("deadline");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_goals");

                    b.HasIndex("EmployeeId", "Status")
                        .HasDatabaseName("ix_goals_employee_id_status");

                    b.ToTable("goals", null, t =>
                        {
                            t.HasCheckConstraint("ck_goals_same_currency", "target_currency = current_currency");

                            t.HasCheckConstraint("ck_goals_target_positive", "target_amount > 0");
                        });
                });

            modelBuilder.Entity("FinGrow.Domain.Entities.Investment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AssetName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("asset_name");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<DateOnly>("PurchasedOn")
                        .HasColumnType("date")
                        .HasColumnName("purchased_on");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<DateTimeOffset>("ValuedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valued_at");

                    b.HasKey("Id")
                        .HasName("pk_investments");

                    b.HasIndex("EmployeeId", "Type")
                        .HasDatabaseName("ix_investments_employee_id_type");

                    b.ToTable("investments", null, t =>
                        {
                            t.HasCheckConstraint("ck_investments_invested_positive", "invested_amount > 0");

                            t.HasCheckConstraint("ck_investments_same_currency", "invested_currency = current_value_currency");
                        });
                });

            modelBuilder.Entity("FinGrow.Domain.Entities.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("description");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<string>("ExpenseCategory")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("expense_category");

                    b.Property<string>("ExternalReference")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("external_reference");

                    b.Property<string>("IncomeCategory")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("income_category");

                    b.Property<DateOnly>("OccurredOn")
                        .HasColumnType("date")
                        .HasColumnName("occurred_on");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("payment_method");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("source");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_transactions");

                    b.HasIndex("EmployeeId", "OccurredOn")
                        .HasDatabaseName("ix_transactions_employee_id_occurred_on");

                    b.HasIndex("EmployeeId", "Status")
                        .HasDatabaseName("ix_transactions_employee_id_status");

                    b.HasIndex("EmployeeId", "Source", "ExternalReference")
                        .IsUnique()
                        .HasDatabaseName("ix_transactions_employee_id_source_external_reference")
                        .HasFilter("external_reference IS NOT NULL");

                    b.ToTable("transactions", null, t =>
                        {
                            t.HasCheckConstraint("ck_transactions_amount_positive", "amount > 0");

                            t.HasCheckConstraint("ck_transactions_category_matches_type", "(type = 'Expense' AND expense_category IS NOT NULL AND income_category IS NULL)\nOR (type = 'Income' AND income_category IS NOT NULL AND expense_category IS NULL)");
                        });
                });

            modelBuilder.Entity("FinGrow.Domain.Entities.Budget", b =>
                {
                    b.HasOne("FinGrow.Domain.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_budgets_employees_employee_id");

                    b.OwnsOne("FinGrow.Domain.ValueObjects.Money", "Limit", b1 =>
                        {
                            b1.Property<Guid>("BudgetId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("limit_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("currency");

                            b1.HasKey("BudgetId")
                                .HasName("pk_budgets");

                            b1.ToTable("budgets");

                            b1.WithOwner()
                                .HasForeignKey("BudgetId")
                                .HasConstraintName("fk_budgets_budgets_id");
                        });

                    b.Navigation("Employee");

                    b.Navigation("Limit")
                        .IsRequired();
                });

            modelBuilder.Entity("FinGrow.Domain.Entities.Department", b =>
                {
                    b.HasOne("FinGrow.Domain.Entities.Company", null)
                        .WithMany("Departments")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_departments_companies_company_id");
                });

            modelBuilder.Entity("FinGrow.Domain.Entities.Employee", b =>
                {
                    b.HasOne("FinGrow.Domain.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_employees_companies_company_id");

                    b.HasOne("FinGrow.Domain.Entities.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_employees_departments_department_id");

                    b.Navigation("Company");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("FinGrow.Domain.Entities.Goal", b =>
                {
                    b.HasOne("FinGrow.Domain.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_goals_employees_employee_id");

                    b.OwnsOne("FinGrow.Domain.ValueObjects.Money", "CurrentAmount", b1 =>
                        {
                            b1.Property<Guid>("GoalId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("current_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("current_currency");

                            b1.HasKey("GoalId")
                                .HasName("pk_goals");

                            b1.ToTable("goals");

                            b1.WithOwner()
                                .HasForeignKey("GoalId")
                                .HasConstraintName("fk_goals_goals_id");
                        });

                    b.OwnsOne("FinGrow.Domain.ValueObjects.Money", "TargetAmount", b1 =>
                        {
                            b1.Property<Guid>("GoalId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("target_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("target_currency");

                            b1.HasKey("GoalId")
                                .HasName("pk_goals");

                            b1.ToTable("goals");

                            b1.WithOwner()
                                .HasForeignKey("GoalId")
                                .HasConstraintName("fk_goals_goals_id");
                        });

                    b.Navigation("CurrentAmount")
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("TargetAmount")
                        .IsRequired();
                });

            modelBuilder.Entity("FinGrow.Domain.Entities.Investment", b =>
                {
                    b.HasOne("FinGrow.Domain.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_investments_employees_employee_id");

                    b.OwnsOne("FinGrow.Domain.ValueObjects.Money", "CurrentValue", b1 =>
                        {
                            b1.Property<Guid>("InvestmentId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("current_value");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("current_value_currency");

                            b1.HasKey("InvestmentId")
                                .HasName("pk_investments");

                            b1.ToTable("investments");

                            b1.WithOwner()
                                .HasForeignKey("InvestmentId")
                                .HasConstraintName("fk_investments_investments_id");
                        });

                    b.OwnsOne("FinGrow.Domain.ValueObjects.Money", "InvestedAmount", b1 =>
                        {
                            b1.Property<Guid>("InvestmentId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("invested_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("invested_currency");

                            b1.HasKey("InvestmentId")
                                .HasName("pk_investments");

                            b1.ToTable("investments");

                            b1.WithOwner()
                                .HasForeignKey("InvestmentId")
                                .HasConstraintName("fk_investments_investments_id");
                        });

                    b.Navigation("CurrentValue")
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("InvestedAmount")
                        .IsRequired();
                });

            modelBuilder.Entity("FinGrow.Domain.Entities.Transaction", b =>
                {
                    b.HasOne("FinGrow.Domain.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_transactions_employees_employee_id");

                    b.OwnsOne("FinGrow.Domain.ValueObjects.Money", "Amount", b1 =>
                        {
                            b1.Property<Guid>("TransactionId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("currency");

                            b1.HasKey("TransactionId")
                                .HasName("pk_transactions");

                            b1.ToTable("transactions");

                            b1.WithOwner()
                                .HasForeignKey("TransactionId")
                                .HasConstraintName("fk_transactions_transactions_id");
                        });

                    b.Navigation("Amount")
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("FinGrow.Domain.Entities.Company", b =>
                {
                    b.Navigation("Departments");
                });
#pragma warning restore 612, 618
        }
    }
}
