// <auto-generated />
using System;
using FinGrow.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FinGrow.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(FinGrowDbContext))]
    partial class FinGrowDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FinGrow.Domain.Entities.Article", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("category");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(50000)
                        .HasColumnType("character varying(50000)")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<int>("ReadingTimeMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("reading_time_minutes");

                    b.Property<string>("RelatedInvestmentType")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("related_investment_type");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("slug");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("summary");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_articles");

                    b.HasIndex("Category")
                        .HasDatabaseName("ix_articles_category");

                    b.HasIndex("RelatedInvestmentType")
                        .HasDatabaseName("ix_articles_related_investment_type");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_articles_slug");

                    b.ToTable("articles", null, t =>
                        {
                            t.HasCheckConstraint("ck_articles_reading_time_positive", "reading_time_minutes > 0");
                        });
                });

            modelBuilder.Entity("FinGrow.Domain.Entities.Budget", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("period");

                    b.Property<DateOnly>("PeriodStart")
                        .HasColumnType("date")
                        .HasColumnName("period_start");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_budgets");

                    b.HasIndex("EmployeeId", "Period", "PeriodStart")
                        .IsUnique()
                        .HasDatabaseName("ix_budgets_employee_id_period_period_start");

                    b.ToTable("budgets", (string)null);
                });

            modelBuilder.Entity("FinGrow.Domain.Entities.BudgetCategoryLimit", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BudgetId")
                        .HasColumnType("uuid")
                        .HasColumnName("budget_id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_budget_category_limits");

                    b.HasIndex("BudgetId", "Category")
                        .IsUnique()
                        .HasDatabaseName("ix_budget_category_limits_budget_id_category");

                    b.ToTable("budget_category_limits", null, t =>
                        {
                            t.HasCheckConstraint("ck_budget_category_limits_limit_positive", "limit_amount > 0");
                        });
                });

            modelBuilder.Entity("FinGrow.Domain.Entities.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DefaultCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("default_currency");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("password_hash");

                    b.Property<string>("TaxId")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("tax_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_companies");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_companies_email");

                    b.HasIndex("TaxId")
                        .IsUnique()
                        .HasDatabaseName("ix_companies_tax_id");

                    b.ToTable("companies", (string)null);
                });

            modelBuilder.Entity("FinGrow.Domain.Entities.CompanyMetricsSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTimeOffset>("ComputedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("computed_at");

                    b.Property<DateOnly>("PeriodStart")
                        .HasColumnType("date")
                        .HasColumnName("period_start");

                    b.HasKey("Id")
                        .HasName("pk_company_metrics_snapshots");

                    b.HasIndex("CompanyId", "PeriodStart")
                        .IsUnique()
                        .HasDatabaseName("ix_company_metrics_snapshots_company_id_period_start");

                    b.ToTable("company_metrics_snapshots", null, t =>
                        {
                            t.HasCheckConstraint("ck_company_metrics_snapshots_period_starts_on_day_one", "extract(day from period_start) = 1");
                        });
                });

            modelBuilder.Entity("FinGrow.Domain.Entities.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("level");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<string>("RelatedInvestmentType")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("related_investment_type");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("slug");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_courses");

                    b.HasIndex("RelatedInvestmentType")
                        .HasDatabaseName("ix_courses_related_investment_type");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_courses_slug");

                    b.HasIndex("Category", "Level")
                        .HasDatabaseName("ix_courses_category_level");

                    b.ToTable("courses", (string)null);
                });

            modelBuilder.Entity("FinGrow.Domain.Entities.CourseRating", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid")
                        .HasColumnName("course_id");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<DateTimeOffset>("RatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rated_at");

                    b.Property<int>("Score")
                        .HasColumnType("integer")
                        .HasColumnName("score");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_course_ratings");

                    b.HasIndex("CourseId")
                        .HasDatabaseName("ix_course_ratings_course_id");

                    b.HasIndex("EmployeeId", "CourseId")
                        .IsUnique()
                        .HasDatabaseName("ix_course_ratings_employee_id_course_id");

                    b.ToTable("course_ratings", null, t =>
                        {
                            t.HasCheckConstraint("ck_course_ratings_score_range", "score BETWEEN 1 AND 5");
                        });
                });

            modelBuilder.Entity("FinGrow.Domain.Entities.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("ManagerName")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("manager_name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_departments");

                    b.HasIndex("CompanyId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_departments_company_id_name");

                    b.ToTable("departments", (string)null);
                });

            modelBuilder.Entity("FinGrow.Domain.Entities.DepartmentMetricsSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTimeOffset>("ComputedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("computed_at");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("department_id");

                    b.Property<DateOnly>("PeriodStart")
                        .HasColumnType("date")
                        .HasColumnName("period_start");

                    b.HasKey("Id")
                        .HasName("pk_department_metrics_snapshots");

                    b.HasIndex("CompanyId", "PeriodStart")
                        .HasDatabaseName("ix_department_metrics_snapshots_company_id_period_start");

                    b.HasIndex("DepartmentId", "PeriodStart")
                        .IsUnique()
                        .HasDatabaseName("ix_department_metrics_snapshots_department_id_period_start");

                    b.ToTable("department_metrics_snapshots", null, t =>
                        {
                            t.HasCheckConstraint("ck_department_metrics_snapshots_period_starts_on_day_one", "extract(day from period_start) = 1");
                        });
                });

            modelBuilder.Entity("FinGrow.Domain.Entities.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DateFormat")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("date_format");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("department_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_name");

                    b.Property<DateOnly>("HiredOn")
                        .HasColumnType("date")
                        .HasColumnName("hired_on");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("language");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("phone_number");

                    b.Property<string>("PreferredCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("preferred_currency");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("theme");

                    b.Property<DateTimeOffset?>("TwoFactorEnabledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("two_factor_enabled_at");

                    b.Property<string>("TwoFactorSecret")
                        .HasColumnType("text")
                        .HasColumnName("two_factor_secret")
                        .HasAnnotation("FinGrow:Encrypted", true);

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_employees");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("ix_employees_company_id");

                    b.HasIndex("DepartmentId")
                        .HasDatabaseName("ix_employees_department_id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_employees_email");

                    b.ToTable("employees", (string)null);
                });

            modelBuilder.Entity("FinGrow.Domain.Entities.EmployeeIntegration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<string>("ExternalAccountId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("external_account_id");

                    b.Property<DateTimeOffset?>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_synced_at");

                    b.Property<DateTimeOffset>("LinkedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("linked_at");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("provider");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_employee_integrations");

                    b.HasIndex("EmployeeId", "Provider")
                        .IsUnique()
                        .HasDatabaseName("ix_employee_integrations_employee_id_provider");

                    b.HasIndex("Provider", "ExternalAccountId")
                        .IsUnique()
                        .HasDatabaseName("ix_employee_integrations_provider_external_account_id");

                    b.ToTable("employee_integrations", (string)null);
                });

            modelBuilder.Entity("FinGrow.Domain.Entities.Goal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AchievedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("achieved_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("Deadline")
                        .HasColumnType("date")
                        .HasColumnName("deadline");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_goals");

                    b.HasIndex("EmployeeId", "Status")
                        .HasDatabaseName("ix_goals_employee_id_status");

                    b.ToTable("goals", null, t =>
                        {
                            t.HasCheckConstraint("ck_goals_target_positive", "target_amount > 0");
                        });
                });

            modelBuilder.Entity("FinGrow.Domain.Entities.GoalContribution", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("ContributedOn")
                        .HasColumnType("date")
                        .HasColumnName("contributed_on");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("GoalId")
                        .HasColumnType("uuid")
                        .HasColumnName("goal_id");

                    b.Property<string>("Note")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("note");

                    b.HasKey("Id")
                        .HasName("pk_goal_contributions");

                    b.HasIndex("GoalId", "ContributedOn")
                        .HasDatabaseName("ix_goal_contributions_goal_id_contributed_on");

                    b.ToTable("goal_contributions", null, t =>
                        {
                            t.HasCheckConstraint("ck_goal_contributions_amount_positive", "amount > 0");
                        });
                });

            modelBuilder.Entity("FinGrow.Domain.Entities.IntegrationLinkCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code_hash");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("provider");

                    b.Property<DateTimeOffset?>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.HasKey("Id")
                        .HasName("pk_integration_link_codes");

                    b.HasIndex("EmployeeId")
                        .HasDatabaseName("ix_integration_link_codes_employee_id");

                    b.HasIndex("Provider", "CodeHash")
                        .IsUnique()
                        .HasDatabaseName("ix_integration_link_codes_provider_code_hash");

                    b.ToTable("integration_link_codes", (string)null);
                });

            modelBuilder.Entity("FinGrow.Domain.Entities.Investment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AssetName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("asset_name");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<DateOnly>("PurchasedOn")
                        .HasColumnType("date")
                        .HasColumnName("purchased_on");

                    b.Property<decimal?>("Quantity")
                        .HasPrecision(30, 10)
                        .HasColumnType("numeric(30,10)")
                        .HasColumnName("quantity");

                    b.Property<string>("Symbol")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("symbol");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_investments");

                    b.HasIndex("EmployeeId", "Type")
                        .HasDatabaseName("ix_investments_employee_id_type");

                    b.ToTable("investments", null, t =>
                        {
                            t.HasCheckConstraint("ck_investments_invested_positive", "invested_amount > 0");

                            t.HasCheckConstraint("ck_investments_quantity_positive", "quantity IS NULL OR quantity > 0");

                            t.HasCheckConstraint("ck_investments_symbol_with_quantity", "(symbol IS NULL) = (quantity IS NULL)");
                        });
                });

            modelBuilder.Entity("FinGrow.Domain.Entities.InvestmentValuation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("InvestmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("investment_id");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("source");

                    b.Property<DateOnly>("ValuedOn")
                        .HasColumnType("date")
                        .HasColumnName("valued_on");

                    b.HasKey("Id")
                        .HasName("pk_investment_valuations");

                    b.HasIndex("InvestmentId", "ValuedOn")
                        .HasDatabaseName("ix_investment_valuations_investment_id_valued_on");

                    b.ToTable("investment_valuations", (string)null);
                });

            modelBuilder.Entity("FinGrow.Domain.Entities.JobRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Error")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("error");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<string>("JobName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("job_name");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Summary")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("summary");

                    b.HasKey("Id")
                        .HasName("pk_job_runs");

                    b.HasIndex("JobName", "StartedAt")
                        .HasDatabaseName("ix_job_runs_job_name_started_at");

                    b.ToTable("job_runs", null, t =>
                        {
                            t.HasCheckConstraint("ck_job_runs_finished_after_started", "finished_at IS NULL OR finished_at >= started_at");
                        });
                });

            modelBuilder.Entity("FinGrow.Domain.Entities.Lesson", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid")
                        .HasColumnName("course_id");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("duration_minutes");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<string>("VideoUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("video_url");

                    b.HasKey("Id")
                        .HasName("pk_lessons");

                    b.HasIndex("CourseId", "Position")
                        .IsUnique()
                        .HasDatabaseName("ix_lessons_course_id_position");

                    b.ToTable("lessons", null, t =>
                        {
                            t.HasCheckConstraint("ck_lessons_duration_positive", "duration_minutes > 0");

                            t.HasCheckConstraint("ck_lessons_position_positive", "position > 0");
                        });
                });

            modelBuilder.Entity("FinGrow.Domain.Entities.LessonCompletion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<Guid>("LessonId")
                        .HasColumnType("uuid")
                        .HasColumnName("lesson_id");

                    b.HasKey("Id")
                        .HasName("pk_lesson_completions");

                    b.HasIndex("LessonId")
                        .HasDatabaseName("ix_lesson_completions_lesson_id");

                    b.HasIndex("EmployeeId", "LessonId")
                        .IsUnique()
                        .HasDatabaseName("ix_lesson_completions_employee_id_lesson_id");

                    b.ToTable("lesson_completions", (string)null);
                });

            modelBuilder.Entity("FinGrow.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DeduplicationKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("deduplication_key");

                    b.Property<DateTimeOffset?>("ReadAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("read_at");

                    b.Property<Guid>("RecipientId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipient_id");

                    b.Property<string>("RecipientType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("recipient_type");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_notifications");

                    b.HasIndex("RecipientType", "RecipientId", "CreatedAt")
                        .HasDatabaseName("ix_notifications_recipient_type_recipient_id_created_at");

                    b.HasIndex("RecipientType", "RecipientId", "Type", "DeduplicationKey", "CreatedAt")
                        .HasDatabaseName("ix_notifications_deduplication");

                    b.ToTable("notifications", null, t =>
                        {
                            t.HasCheckConstraint("ck_notifications_read_after_created", "read_at IS NULL OR read_at >= created_at");
                        });
                });

            modelBuilder.Entity("FinGrow.Domain.Entities.NotificationChannelSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("channel");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_notification_channel_settings");

                    b.HasIndex("EmployeeId", "Channel")
                        .IsUnique()
                        .HasDatabaseName("ix_notification_channel_settings_employee_id_channel");

                    b.ToTable("notification_channel_settings", null, t =>
                        {
                            t.HasCheckConstraint("ck_notification_channel_settings_configurable_channel", "channel <> 'InApp'");
                        });
                });

            modelBuilder.Entity("FinGrow.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("ix_refresh_tokens_company_id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_token_hash");

                    b.HasIndex("UserId", "RevokedAt")
                        .HasDatabaseName("ix_refresh_tokens_user_id_revoked_at");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("FinGrow.Domain.Entities.SecurityPrice", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<string>("Market")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("market");

                    b.Property<DateOnly>("PricedOn")
                        .HasColumnType("date")
                        .HasColumnName("priced_on");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("source");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("symbol");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(30, 12)
                        .HasColumnType("numeric(30,12)")
                        .HasColumnName("unit_price");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_security_prices");

                    b.HasIndex("Market", "Symbol", "Currency")
                        .IsUnique()
                        .HasDatabaseName("ix_security_prices_market_symbol_currency");

                    b.ToTable("security_prices", null, t =>
                        {
                            t.HasCheckConstraint("ck_security_prices_unit_price_positive", "unit_price > 0");
                        });
                });

            modelBuilder.Entity("FinGrow.Domain.Entities.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("description");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<string>("ExpenseCategory")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("expense_category");

                    b.Property<string>("ExternalReference")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("external_reference");

                    b.Property<string>("IncomeCategory")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("income_category");

                    b.Property<DateOnly>("OccurredOn")
                        .HasColumnType("date")
                        .HasColumnName("occurred_on");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("payment_method");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("source");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_transactions");

                    b.HasIndex("EmployeeId", "OccurredOn")
                        .HasDatabaseName("ix_transactions_employee_id_occurred_on");

                    b.HasIndex("EmployeeId", "Status")
                        .HasDatabaseName("ix_transactions_employee_id_status");

                    b.HasIndex("EmployeeId", "Source", "ExternalReference")
                        .IsUnique()
                        .HasDatabaseName("ix_transactions_employee_id_source_external_reference")
                        .HasFilter("external_reference IS NOT NULL");

                    b.ToTable("transactions", null, t =>
                        {
                            t.HasCheckConstraint("ck_transactions_amount_positive", "amount > 0");

                            t.HasCheckConstraint("ck_transactions_category_matches_type", "(type = 'Expense' AND expense_category IS NOT NULL AND income_category IS NULL)\r\nOR (type = 'Income' AND income_category IS NOT NULL AND expense_category IS NULL)");
                        });
                });

            modelBuilder.Entity("FinGrow.Domain.Entities.Budget", b =>
                {
                    b.HasOne("FinGrow.Domain.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_budgets_employees_employee_id");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("FinGrow.Domain.Entities.BudgetCategoryLimit", b =>
                {
                    b.HasOne("FinGrow.Domain.Entities.Budget", null)
                        .WithMany("Limits")
                        .HasForeignKey("BudgetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_budget_category_limits_budgets_budget_id");

                    b.OwnsOne("FinGrow.Domain.ValueObjects.Money", "Limit", b1 =>
                        {
                            b1.Property<Guid>("BudgetCategoryLimitId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("limit_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("currency");

                            b1.HasKey("BudgetCategoryLimitId")
                                .HasName("pk_budget_category_limits");

                            b1.ToTable("budget_category_limits");

                            b1.WithOwner()
                                .HasForeignKey("BudgetCategoryLimitId")
                                .HasConstraintName("fk_budget_category_limits_budget_category_limits_id");
                        });

                    b.Navigation("Limit")
                        .IsRequired();
                });

            modelBuilder.Entity("FinGrow.Domain.Entities.CompanyMetricsSnapshot", b =>
                {
                    b.HasOne("FinGrow.Domain.Entities.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_company_metrics_snapshots_companies_company_id");

                    b.OwnsOne("FinGrow.Domain.ValueObjects.PeriodMetrics", "Metrics", b1 =>
                        {
                            b1.Property<Guid>("CompanyMetricsSnapshotId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<int>("ActiveEmployees")
                                .HasColumnType("integer")
                                .HasColumnName("active_employees");

                            b1.Property<int>("ConfirmedTransactions")
                                .HasColumnType("integer")
                                .HasColumnName("confirmed_transactions");

                            b1.Property<int>("EmployeesWithActiveGoal")
                                .HasColumnType("integer")
                                .HasColumnName("employees_with_active_goal");

                            b1.Property<int>("EmployeesWithBudget")
                                .HasColumnType("integer")
                                .HasColumnName("employees_with_budget");

                            b1.Property<int>("EmployeesWithIntegration")
                                .HasColumnType("integer")
                                .HasColumnName("employees_with_integration");

                            b1.Property<int>("GoalsAchieved")
                                .HasColumnType("integer")
                                .HasColumnName("goals_achieved");

                            b1.Property<int>("ParticipatingEmployees")
                                .HasColumnType("integer")
                                .HasColumnName("participating_employees");

                            b1.HasKey("CompanyMetricsSnapshotId")
                                .HasName("pk_company_metrics_snapshots");

                            b1.ToTable("company_metrics_snapshots");

                            b1.WithOwner()
                                .HasForeignKey("CompanyMetricsSnapshotId")
                                .HasConstraintName("fk_company_metrics_snapshots_company_metrics_snapshots_id");
                        });

                    b.Navigation("Metrics")
                        .IsRequired();
                });

            modelBuilder.Entity("FinGrow.Domain.Entities.CourseRating", b =>
                {
                    b.HasOne("FinGrow.Domain.Entities.Course", null)
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_course_ratings_courses_course_id");

                    b.HasOne("FinGrow.Domain.Entities.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_course_ratings_employees_employee_id");
                });

            modelBuilder.Entity("FinGrow.Domain.Entities.Department", b =>
                {
                    b.HasOne("FinGrow.Domain.Entities.Company", null)
                        .WithMany("Departments")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_departments_companies_company_id");
                });

            modelBuilder.Entity("FinGrow.Domain.Entities.DepartmentMetricsSnapshot", b =>
                {
                    b.HasOne("FinGrow.Domain.Entities.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_department_metrics_snapshots_companies_company_id");

                    b.HasOne("FinGrow.Domain.Entities.Department", null)
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_department_metrics_snapshots_departments_department_id");

                    b.OwnsOne("FinGrow.Domain.ValueObjects.PeriodMetrics", "Metrics", b1 =>
                        {
                            b1.Property<Guid>("DepartmentMetricsSnapshotId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<int>("ActiveEmployees")
                                .HasColumnType("integer")
                                .HasColumnName("active_employees");

                            b1.Property<int>("ConfirmedTransactions")
                                .HasColumnType("integer")
                                .HasColumnName("confirmed_transactions");

                            b1.Property<int>("EmployeesWithActiveGoal")
                                .HasColumnType("integer")
                                .HasColumnName("employees_with_active_goal");

                            b1.Property<int>("EmployeesWithBudget")
                                .HasColumnType("integer")
                                .HasColumnName("employees_with_budget");

                            b1.Property<int>("EmployeesWithIntegration")
                                .HasColumnType("integer")
                                .HasColumnName("employees_with_integration");

                            b1.Property<int>("GoalsAchieved")
                                .HasColumnType("integer")
                                .HasColumnName("goals_achieved");

                            b1.Property<int>("ParticipatingEmployees")
                                .HasColumnType("integer")
                                .HasColumnName("participating_employees");

                            b1.HasKey("DepartmentMetricsSnapshotId")
                                .HasName("pk_department_metrics_snapshots");

                            b1.ToTable("department_metrics_snapshots");

                            b1.WithOwner()
                                .HasForeignKey("DepartmentMetricsSnapshotId")
                                .HasConstraintName("fk_department_metrics_snapshots_department_metrics_snapshots_id");
                        });

                    b.Navigation("Metrics")
                        .IsRequired();
                });

            modelBuilder.Entity("FinGrow.Domain.Entities.Employee", b =>
                {
                    b.HasOne("FinGrow.Domain.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_employees_companies_company_id");

                    b.HasOne("FinGrow.Domain.Entities.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_employees_departments_department_id");

                    b.Navigation("Company");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("FinGrow.Domain.Entities.EmployeeIntegration", b =>
                {
                    b.HasOne("FinGrow.Domain.Entities.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_employee_integrations_employees_employee_id");

                    b.OwnsOne("FinGrow.Domain.ValueObjects.OAuthGrant", "Grant", b1 =>
                        {
                            b1.Property<Guid>("EmployeeIntegrationId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("AccessToken")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("oauth_access_token")
                                .HasAnnotation("FinGrow:Encrypted", true);

                            b1.Property<DateTimeOffset>("ExpiresAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("oauth_expires_at");

                            b1.Property<string>("RefreshToken")
                                .HasColumnType("text")
                                .HasColumnName("oauth_refresh_token")
                                .HasAnnotation("FinGrow:Encrypted", true);

                            b1.HasKey("EmployeeIntegrationId")
                                .HasName("pk_employee_integrations");

                            b1.ToTable("employee_integrations");

                            b1.WithOwner()
                                .HasForeignKey("EmployeeIntegrationId")
                                .HasConstraintName("fk_employee_integrations_employee_integrations_id");
                        });

                    b.Navigation("Grant");
                });

            modelBuilder.Entity("FinGrow.Domain.Entities.Goal", b =>
                {
                    b.HasOne("FinGrow.Domain.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_goals_employees_employee_id");

                    b.OwnsOne("FinGrow.Domain.ValueObjects.Money", "TargetAmount", b1 =>
                        {
                            b1.Property<Guid>("GoalId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("target_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("target_currency");

                            b1.HasKey("GoalId")
                                .HasName("pk_goals");

                            b1.ToTable("goals");

                            b1.WithOwner()
                                .HasForeignKey("GoalId")
                                .HasConstraintName("fk_goals_goals_id");
                        });

                    b.Navigation("Employee");

                    b.Navigation("TargetAmount")
                        .IsRequired();
                });

            modelBuilder.Entity("FinGrow.Domain.Entities.GoalContribution", b =>
                {
                    b.HasOne("FinGrow.Domain.Entities.Goal", null)
                        .WithMany("Contributions")
                        .HasForeignKey("GoalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_goal_contributions_goals_goal_id");

                    b.OwnsOne("FinGrow.Domain.ValueObjects.Money", "Amount", b1 =>
                        {
                            b1.Property<Guid>("GoalContributionId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("currency");

                            b1.HasKey("GoalContributionId")
                                .HasName("pk_goal_contributions");

                            b1.ToTable("goal_contributions");

                            b1.WithOwner()
                                .HasForeignKey("GoalContributionId")
                                .HasConstraintName("fk_goal_contributions_goal_contributions_id");
                        });

                    b.Navigation("Amount")
                        .IsRequired();
                });

            modelBuilder.Entity("FinGrow.Domain.Entities.IntegrationLinkCode", b =>
                {
                    b.HasOne("FinGrow.Domain.Entities.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_integration_link_codes_employees_employee_id");
                });

            modelBuilder.Entity("FinGrow.Domain.Entities.Investment", b =>
                {
                    b.HasOne("FinGrow.Domain.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_investments_employees_employee_id");

                    b.OwnsOne("FinGrow.Domain.ValueObjects.Money", "InvestedAmount", b1 =>
                        {
                            b1.Property<Guid>("InvestmentId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("invested_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("invested_currency");

                            b1.HasKey("InvestmentId")
                                .HasName("pk_investments");

                            b1.ToTable("investments");

                            b1.WithOwner()
                                .HasForeignKey("InvestmentId")
                                .HasConstraintName("fk_investments_investments_id");
                        });

                    b.Navigation("Employee");

                    b.Navigation("InvestedAmount")
                        .IsRequired();
                });

            modelBuilder.Entity("FinGrow.Domain.Entities.InvestmentValuation", b =>
                {
                    b.HasOne("FinGrow.Domain.Entities.Investment", null)
                        .WithMany("Valuations")
                        .HasForeignKey("InvestmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_investment_valuations_investments_investment_id");

                    b.OwnsOne("FinGrow.Domain.ValueObjects.Money", "Value", b1 =>
                        {
                            b1.Property<Guid>("InvestmentValuationId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("value");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("currency");

                            b1.HasKey("InvestmentValuationId")
                                .HasName("pk_investment_valuations");

                            b1.ToTable("investment_valuations");

                            b1.WithOwner()
                                .HasForeignKey("InvestmentValuationId")
                                .HasConstraintName("fk_investment_valuations_investment_valuations_id");
                        });

                    b.Navigation("Value")
                        .IsRequired();
                });

            modelBuilder.Entity("FinGrow.Domain.Entities.Lesson", b =>
                {
                    b.HasOne("FinGrow.Domain.Entities.Course", null)
                        .WithMany("Lessons")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lessons_courses_course_id");
                });

            modelBuilder.Entity("FinGrow.Domain.Entities.LessonCompletion", b =>
                {
                    b.HasOne("FinGrow.Domain.Entities.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lesson_completions_employees_employee_id");

                    b.HasOne("FinGrow.Domain.Entities.Lesson", null)
                        .WithMany()
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lesson_completions_lessons_lesson_id");
                });

            modelBuilder.Entity("FinGrow.Domain.Entities.NotificationChannelSetting", b =>
                {
                    b.HasOne("FinGrow.Domain.Entities.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notification_channel_settings_employees_employee_id");
                });

            modelBuilder.Entity("FinGrow.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("FinGrow.Domain.Entities.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_companies_company_id");
                });

            modelBuilder.Entity("FinGrow.Domain.Entities.Transaction", b =>
                {
                    b.HasOne("FinGrow.Domain.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_transactions_employees_employee_id");

                    b.OwnsOne("FinGrow.Domain.ValueObjects.Money", "Amount", b1 =>
                        {
                            b1.Property<Guid>("TransactionId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("currency");

                            b1.HasKey("TransactionId")
                                .HasName("pk_transactions");

                            b1.ToTable("transactions");

                            b1.WithOwner()
                                .HasForeignKey("TransactionId")
                                .HasConstraintName("fk_transactions_transactions_id");
                        });

                    b.Navigation("Amount")
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("FinGrow.Domain.Entities.Budget", b =>
                {
                    b.Navigation("Limits");
                });

            modelBuilder.Entity("FinGrow.Domain.Entities.Company", b =>
                {
                    b.Navigation("Departments");
                });

            modelBuilder.Entity("FinGrow.Domain.Entities.Course", b =>
                {
                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("FinGrow.Domain.Entities.Goal", b =>
                {
                    b.Navigation("Contributions");
                });

            modelBuilder.Entity("FinGrow.Domain.Entities.Investment", b =>
                {
                    b.Navigation("Valuations");
                });
#pragma warning restore 612, 618
        }
    }
}
